apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devpulse
  namespace: devpulse-dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: devpulse
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - devpulse-dev
