apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devpulse-dev
resources:
  - ../../base
images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/devpulse-images/devpulse
    newTag: latest
replicas:
  - name: devpulse
    count: 1
